blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogUpdateView, BlogListView, BlogDetailView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('list/', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

clients/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from clients.apps import ClientsConfig
from clients.views import ClientsCreateView, ClientsDetailView, ClientsListView, ClientsUpdateView, ClientsDeleteView, \
    EmailSettingsDeleteView, EmailSettingsCreateView, EmailSettingsListView, EmailSettingsUpdateView, HomePageView, \
    MailingMessageCreateView, MailingMessageListView, MailingMessageUpdateView, MailingMessageDeleteView, \
    MailLogListView, MailingClientListView, toggle_client

app_name = ClientsConfig.name

urlpatterns = [
    path('clients/home_page/', HomePageView.as_view(), name='main_page'),

    path('clients/create/', ClientsCreateView.as_view(), name='client_create'),
    path('clients/detail/<int:pk>/', ClientsDetailView.as_view(), name='client_detail'),
    path('clients/list/', cache_page(60)(ClientsListView.as_view()), name='client_list'),
    path('clients/update/<int:pk>/', ClientsUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>/', ClientsDeleteView.as_view(), name='client_delete'),

    path('settings/create/', EmailSettingsCreateView.as_view(), name='emailsettings_create'),
    path('settings/list/', cache_page(60)(EmailSettingsListView.as_view()), name='emailsettings_list'),
    path('settings/update/<int:pk>/', EmailSettingsUpdateView.as_view(), name='emailsettings_update'),
    path('settings/delete/<int:pk>/', EmailSettingsDeleteView.as_view(), name='emailsettings_delete'),
    path('settings/edit/<int:pk>/', EmailSettingsUpdateView.edit_activate, name='emailsettings_edit'),

    path('message/create/', MailingMessageCreateView.as_view(), name='mailingmessage_create'),
    path('message/list/', MailingMessageListView.as_view(), name='mailingmessage_list'),
    path('message/update/<int:pk>/', MailingMessageUpdateView.as_view(), name='mailingmessage_update'),
    path('message/delete/<int:pk>/', MailingMessageDeleteView.as_view(), name='mailingmessage_delete'),

    path('mail_log/list/', MailLogListView.as_view(), name='maillog_list'),

    path('mailing_client/list/', MailingClientListView.as_view(), name='mailingclient_list'),
    path('settings/clients/<int:client_pk>', toggle_client, name='mailing_client_toggle'),


]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('version/', include('version.urls', namespace='version')),
    path('users/', include('users.urls', namespace='users')),
    path('clients/', include('clients.urls', namespace='clients')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/models.py
import datetime

from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    first_name = models.CharField(max_length=20, verbose_name='Имя', help_text='Введите имя')
    last_name = models.CharField(max_length=35, verbose_name='Фамилия', help_text='Введите фамилию')
    email = models.EmailField(unique=True, verbose_name='Почта', help_text='Введите email')
    comment = models.TextField(verbose_name='Комментарий', help_text='Укажите комментарий', **NULLABLE)

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Пользователь')
    is_blocked = models.BooleanField(default=False, verbose_name='Блокировка клиента')

    def __str__(self):
        return f'{self.first_name} {self.last_name} - {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class MailingMessage(models.Model):
    letter_subject = models.CharField(max_length=100, verbose_name='Тема письма')
    letter_body = models.TextField(verbose_name='Тело письма')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE,
                              verbose_name='Пользователь')
    client = models.ManyToManyField(Client, verbose_name='Клиент')


    def __str__(self):
        return f'Тема: {self.letter_subject}'

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'


class EmailSettings(models.Model):
    PERIOD_DAILY = 'Ежедневная'
    PERIOD_WEEKLY = 'Раз в неделю'
    PERIOD_MONTHLY = 'Раз в месяц'

    PERIODS = (
        (PERIOD_DAILY, 'Ежедневная'),
        (PERIOD_WEEKLY, 'Раз в неделю'),
        (PERIOD_MONTHLY, 'Раз в месяц'),
    )

    STATUS_CREATED = 'Создана'
    STATUS_STARTED = 'Запущена'
    STATUS_DONE = 'Завершена'

    STATUSES = (
        (STATUS_CREATED, 'Создана'),
        (STATUS_STARTED, 'Запущена'),
        (STATUS_DONE, 'Завершена'),
    )

    start_time = models.DateTimeField(verbose_name='Время старта', **NULLABLE,
                                      default=datetime.datetime.now(datetime.timezone.utc))
    stop_time = models.DateTimeField(verbose_name='Время окончания', **NULLABLE,
                                     default=datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(days=7))
    period = models.CharField(max_length=20, choices=PERIODS, default=PERIOD_DAILY, verbose_name='Период')
    status = models.CharField(max_length=20, choices=STATUSES, default=STATUS_CREATED, verbose_name='Статус')

    message = models.ForeignKey(MailingMessage, on_delete=models.CASCADE, verbose_name='Сообщение', **NULLABLE)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE,
                              verbose_name='Пользователь')
    is_on = models.BooleanField(default=True, verbose_name='Активация рассылки')

    def __str__(self):
        return f'{self.start_time} / {self.period}'

    class Meta:
        verbose_name = 'Настройка'
        verbose_name_plural = 'Настройки'
        # # Отключение рассылок
        # permissions = [
        #     ('set_status',
        #      'Can change status')
        # ]

class MailLog(models.Model):
    STATUS_OK = 'Успешно'
    STATUS_FAILED = 'Ошибка'

    STATUSES = (
        (STATUS_OK, 'Успешно'),
        (STATUS_FAILED, 'Ошибка'),
    )

    last_attempt = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')
    try_status = models.CharField(choices=STATUSES, default=STATUS_OK, verbose_name='Статус попытки')
    mailing_service_response = models.TextField(verbose_name='Ответ почтового сервера, если он был', **NULLABLE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Клиент')

    mailing = models.ForeignKey(EmailSettings, on_delete=models.CASCADE, verbose_name='Рассылка')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE,
                              verbose_name='Пользователь')

    def __str__(self):
        return f'{self.last_attempt} - {self.try_status}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

class MailingClient(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='клиент')
    mailing = models.ForeignKey(EmailSettings, on_delete=models.CASCADE, verbose_name='рассылка')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE,
                              verbose_name='Пользователь')

    def __str__(self):
        return f'{self.client} - {self.mailing}'

    class Meta:
        verbose_name = 'Список рассылки'
        verbose_name_plural = 'Списки рассылок'

clients/forms.py
from catalog.forms import StyleFormMixin
from django import forms

from clients.models import Client, EmailSettings, MailingMessage


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('owner',)

class EmailSettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = EmailSettings
        exclude = "__all__"

class MailingMessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingMessage
        fields = "__all__"

clients/views.py
import random

from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.db.models import Max
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView, TemplateView

from blog.models import Blog
from clients.forms import ClientForm, EmailSettingsForm, MailingMessageForm
from clients.models import Client, EmailSettings, MailLog, MailingMessage, MailingClient


class HomePageView(TemplateView):
    template_name = 'clients/home_page.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        all_email = EmailSettings.objects.all().count()
        is_on_email = EmailSettings.objects.filter(status__in=['Создана', 'Запущена']).count()
        unique_clients = Client.objects.values('email').distinct().count()
        blogs = Blog.objects.order_by('slug')[:3]
        context = {'all_email': all_email, 'is_on_email': is_on_email, 'unique_clients': unique_clients, 'blogs':blogs}
        return context



class ClientsCreateView(CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('clients:client_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientsDetailView(DetailView):
    model = Client
    success_url = reverse_lazy('clients:client_list')


class ClientsListView(ListView):
    model = Client

    def get_queryset(self):
        if self.request.user.is_staff or self.request.user.is_superuser:
            return Client.objects.all()
        else:
            return Client.objects.filter(owner=self.request.user)


class ClientsUpdateView(UserPassesTestMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('clients:client_list')

    def test_func(self):
        return self.request.user == self.get_object().owner or self.request.user.is_superuser or self.request.user.is_staff


class ClientsDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('clients:client_list')


class EmailSettingsCreateView(CreateView):
    model = EmailSettings
    form_class = EmailSettingsForm
    success_url = reverse_lazy('clients:emailsettings_list')


class EmailSettingsListView(ListView):
    model = EmailSettings


class EmailSettingsDeleteView(DeleteView):
    model = EmailSettings
    permission_required = 'clients.delete_emailsettings'


class EmailSettingsUpdateView(UpdateView):
    model = EmailSettings
    form_class = EmailSettingsForm
    success_url = reverse_lazy('clients:emailsettings_list')

    @staticmethod
    def edit_activate(request, pk):
        mailing_item = get_object_or_404(EmailSettings, pk=pk)
        if mailing_item.status == EmailSettings.STATUS_CREATED or mailing_item.status == EmailSettings.STATUS_STARTED:
            mailing_item.status = EmailSettings.STATUS_DONE
        else:
            mailing_item.status = EmailSettings.STATUS_STARTED
        mailing_item.save()
        return redirect('clients:emailsettings_list')


class MailingMessageCreateView(CreateView):
    model = MailingMessage
    form_class = MailingMessageForm
    success_url = reverse_lazy('clients:mailingmessage_list')


class MailingMessageUpdateView(UpdateView):
    model = MailingMessage
    form_class = MailingMessageForm
    success_url = reverse_lazy('clients:mailingmessage_list')


class MailingMessageListView(ListView):
    model = MailingMessage
    success_url = reverse_lazy('clients:mailingmessage_list')


class MailingMessageDeleteView(DeleteView):
    model = MailingMessage
    success_url = reverse_lazy('clients:mailingmessage_list')


class MailLogListView(PermissionRequiredMixin, ListView):
    model = MailLog
    permission_required = 'clients.change_maillog'

    def get_queryset(self):
        if self.request.user.is_staff or self.request.user.is_admin:
            return MailLog.objects.all()
        else:
            return MailLog.objects.filter(owner=self.request.user)


class MailingClientListView(ListView):
    model = MailingClient


def toggle_client(request, pk, client_pk):
    if MailingClient.objects.filter(
            client_id=client_pk,
            mailing_id=pk
    ).exists():
        MailingClient.objects.filter(
            client_id=client_pk,
            mailing_id=pk
        ).delete()
    else:
        MailingClient.objects.create(
            client_id=client_pk,
            mailing_id=pk
        )

    return redirect(reverse('clients:mailingclient_list', args=[pk]))

clients/templates/clients/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Рассылки для клиентов</title>
    <link href="{% static 'css/bootstrap.min.css' %} " rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылки для клиентов</h1>
</div>


<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                    <li><a class="text-muted" href="/admin/">admin</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

clients/templates/clients/client_confirm_delete.html
{% extends 'clients/base.html' %}

{% block content %}
<div class="container">
    <div class="row text">
        <div class="col-12">
            <div class="row">
                <div class="col-4">
                    <div class="card">
                        <p class="p-3 border bg-light">Действительно удалить {{ object.name }} ?</p>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Удалить</button>
                                <a class="btn btn-primary" href="{% url 'clients:client_list' %}"
                                   role="button">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

clients/templates/clients/client_form.html
{% extends 'clients/base.html' %}

{% block content %}
<div class="container">
    <div class="row text">
        <div class="col-6">
            <div class="row">
                <div class="card-deck">
                    <div class="card-align-self-end">
                        <form class="text-body-color mb-3 form-control" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}

                            </button>
                            <a class="btn btn-primary" href="{% url 'clients:client_list' %}"
                               role="button">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

clients/templates/clients/client_list.html
{% extends 'clients/base.html' %}
{% block content %}
{% for object in object_list %}
<div class="col-12">
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-1">
        <div class="col">
            <div class="card bg-transparent h-100">
                <div class="card-header">
                    <h5 class="card-title">{{ object.email }}</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ object.first_name }} {{ object.last_name }}</p>
                    <p class="card-text">{{ object.comment }}</p>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col">
                            <div role="button" aria-label="Basic outlined example">
                                {% if perms.clients.change_client or object.owner == user %}
                                    <a href="{% url 'clients:client_update' object.pk %}"
                                       class="btn btn-outline-success">Изменить</a>
                                {% endif %}
                                {% if perms.clients.delete_client or object.owner == user %}
                                    <a href="{% url 'clients:client_delete' object.pk %}"
                                       class="btn btn-outline-danger">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div class="card-align-self-end mt-3">
    <div class="card-body">
        <a href="{% url 'clients:main_page' %}" type="button"
           class="btn btn-lg btn-block btn-danger">Назад</a>
    </div>
</div>
{% endblock %}

clients/templates/clients/emailsettings_confirm_delete.html
{% extends 'clients/base.html' %}

{% block content %}
<div class="container">
    <div class="row text">
        <div class="col-12">
            <div class="row">
                <div class="col-4">
                    <div class="card">
                        <p class="p-3 border bg-light">Действительно удалить {{ object.name }} ?</p>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Удалить</button>
                                <a class="btn btn-primary" href="{% url 'clients:emailsettings_list' %}"
                                   role="button">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

clients/templates/clients/emailsettings_form.html
{% extends 'clients/base.html' %}

{% block content %}
<div class="container">
    <div class="row text">
        <div class="col-6">
            <div class="row">
                <div class="card-deck">
                    <div class="card-align-self-end">
                        <form class="text-body-color mb-3 form-control" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                            <a class="btn btn-primary" href="{% url 'clients:emailsettings_list' %}"
                               role="button">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-align-self-end mt-3">
        <div class="card-body">
            <a href="{% url 'clients:main_page' %}" type="button"
               class="btn btn-lg btn-block btn-danger">Назад</a>
        </div>
    </div>
    {% endblock %}

clients/templates/clients/emailsettings_list.html
{% extends 'clients/base.html' %}

{% block content %}

{% for object in object_list %}
<div class="col-12">
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-1">
        <div class="col">
            <div class="card bg-transparent h-100">
                <div class="card-header">
                    <h5 class="card-title">{{ object.start_time }}</h5>
                    <h5 class="card-title">{{ object.stop_time }}</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ object.status }}</p>
                    <p class="card-text">{{ object.period }}</p>
                    <p class="card-text">{{ object.message }}</p>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col">
                            <div role="button" aria-label="Basic outlined example">
                                {% if perms.clients.change_emailsettings or object.owner == user %}
                                <a href="{% url 'clients:emailsettings_update' object.pk %}"
                                   class="btn btn-outline-success">Изменить</a>
                                {% endif %}
                                {% if perms.clients.delete_emailsettings or object.owner == user %}
                                <a href="{% url 'clients:emailsettings_delete' object.pk %}"
                                   class="btn btn-outline-danger">Удалить</a>
                                {% endif %}
                                {% if object.status == 'Создана' or object.status == 'Запущена' %}
                                <a href="{% url 'clients:emailsettings_edit' object.pk %}"
                                   class="btn btn-outline-primary">Остановить рассылку</a>
                                {% else %}
                                <a href="{% url 'clients:emailsettings_edit' object.pk %}"
                                   class="btn btn-outline-primary">Активировать</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div class="card-align-self-end mt-3">
    <div class="card-body">
        <a href="{% url 'clients:main_page' %}" type="button"
           class="btn btn-lg btn-block btn-danger">Назад</a>
    </div>
</div>

{% endblock %}

clients/templates/clients/home_page.html
{% extends 'clients/base.html' %}
{% load my_tags %}
{% block content %}
<div style="margin-top: 50px">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary mx-auto mb-3" href="{% url 'clients:client_create' %}">Добавить клиента</a>
    <a class="btn btn-outline-primary mx-auto mb-3" href="{% url 'clients:emailsettings_create' %}">Создать
        рассылку</a>
    <a class="btn btn-outline-primary mx-auto mb-3" href="{% url 'clients:mailingmessage_create' %}">Создать сообщение
        для отправки</a>
    <a class="btn btn-outline-primary mx-auto mb-3" href="{% url 'clients:maillog_list' %}">Информация о рассылках</a>
    <a class="btn btn-outline-primary mx-auto mb-3" href="{% url 'clients:client_list' %}">Список клиентов</a>
    <a class="btn btn-outline-primary mx-auto mb-3" href="{% url 'clients:emailsettings_list' %}">Список рассылок</a>

    <div style="margin-top: 50px">

        <table class="table table-striped" style="vertical-align:middle">
            <thead>
            <tr>
                <th>Количество рассылок всего</th>
                <th>Количество активных рассылок</th>
                <th>Количество уникальных клиентов для рассылок</th>
            </tr>
            </thead>
            <tbody class="table-group-divider">
            <tr>
                <td>{{ all_email }}</td>
                <td>{{ is_on_email }}</td>
                <td>{{ unique_clients }}</td>
            </tr>
            </tbody>
        </table>
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="card mb-4 mt-4 box-shadow">
                        <h4 class="my-0 font-weight-normal text-center">
                            Три случайные статьи из блога
                        </h4>
                        {% for blog in blogs %}
                        <div class="card-header">
                            <h5 class="card-title">{{ blog.title }}</h5>
                        </div>
                        <div class="card-body">
                            <img class="card-img-top" src="{{ blog.preview | media_filter }}" width="200" height="600">
                            <p class="text-start">{{ object.content }}</p>
                        </div>
                        {% empty %}
                        Нет постов.
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% if not user.is_authenticated %}
                    <div class="alert alert-danger" role="alert">
                        Для просмотра и редактирования клиентов необходимо авторизоваться.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

        {% endblock %}

clients/templates/clients/mailingclient_list.html
{% extends "clients/base.html" %}
{% block content %}

<div class="row">
    <div class="col-6">
        <div class="col-12 mb-5">
            <p align="center"> Клиенты рассылки</p>
        </div>
        {% for object in object_list %}
        <div class="card bg-transparent">
            <div class="card-header">
                {{ object.client.first_name }}
                {{ object.client.last_name }}
            </div>
            <div class="card-body">
                {{ object.client.email}}
            </div>
            <div class="card-footer">
                <a href="{% url 'clients:mailing_client_toggle' object.client.pk %}"
                       class="btn btn-outline-secondary">Удалить</a>
            </div>
        </div>
        {% endfor %}
    </div>


    <div class="col-6">
        <div class="col-12 mb-5">
            <p align="center"> Клиенты для добавления </p>
        </div>
        <table class="table">
            <tr>
                <th>Фамилия</th>
                <th>Имя</th>
                <th>Email</th>
                <th>Добавить</th>
            </tr>
            {% for client in clients %}
            <tr>
                <td>{{ client.last_name }}</td>
                <td>{{ client.first_name }}</td>
                <td>{{ client.email }}</td>
                <td><a href="{% url 'clients:mailing_client_toggle' client.pk %}"
                       class="btn btn-outline-secondary">Добавить</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
<div class="card-align-self-end mt-3">
    <div class="card-body">
        <a href="{% url 'clients:main_page' %}" type="button"
           class="btn btn-lg btn-block btn-danger">Назад</a>
    </div>
</div>
{% endblock %}

clients/templates/clients/mailingmessage_list.html
{% extends 'clients/base.html' %}

{% block content %}

{% for object in object_list %}
<div class="col-12">
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-1">
        <div class="col">
            <div class="card bg-transparent h-100">
                <div class="card-header">
                    <h5 class="card-title">{{ object.letter_subject }}</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ object.letter_body }}</p>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col">
                            {% if perms.clients.change_mailingmessage or object.owner == user %}
                            <div role="button" aria-label="Basic outlined example">
                                <a href="{% url 'clients:mailingmessage_update' object.pk %}"
                                   class="btn btn-outline-success">Изменить</a>
                                <a href="{% url 'clients:mailingmessage_delete' object.pk %}"
                                   class="btn btn-outline-danger">Удалить</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div class="card-align-self-end mt-3">
    <div class="card-body">
        <a href="{% url 'clients:main_page' %}" type="button"
           class="btn btn-lg btn-block btn-danger">Назад</a>
    </div>
</div>

{% endblock %}

clients/templates/clients/maillog_list.html
{% extends 'clients/base.html' %}

{% block content %}
<div style="margin-top: 50px">

    <table class="table table-striped" style="vertical-align:middle">
        <thead>
        <tr>
            <th>Дата и время последней попытки</th>
            <th>Статус попытки</th>
            <th>Ответ почтового сервера</th>
            <th>Клиент</th>
            <th>Рассылка</th>
            <th></th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
        {% for object in object_list %}
        <tr>
            <td>{{ object.last_attempt }}</td>
            <td>{{ object.try_status }}</td>
            <td>{{ object.mailing_service_response }}</td>
            <td>{{ object.client }}</td>
            <td>{{ object.mailing }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="card-align-self-end mt-3">
    <div class="card-body">
        <a href="{% url 'clients:main_page' %}" type="button"
           class="btn btn-lg btn-block btn-danger">Назад</a>
    </div>
</div>
{% endblock %}